'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Client={id:string;name:string|null;username:string|null;preferred_name:string|null;service_interest:string|null;budget:string|null;lead_stage:string|null;last_agreement:string|null};
type Conversation={id:string;client_id:string;control_mode:string;handoff_reason:string|null;last_message_at:string|null};
type Message={id:string;role:string;content:string;created_at:string};

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const db=createClient(supabaseUrl,supabaseKey);

export default function Home(){
 const [clients,setClients]=useState<Client[]>([]); const [selected,setSelected]=useState<Client|null>(null); const [conversation,setConversation]=useState<Conversation|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(''); const [loading,setLoading]=useState(true);
 const load=async()=>{const {data}=await db.from('clients').select('id,name,username,preferred_name,service_interest,budget,lead_stage,last_agreement').eq('channel','telegram').order('last_contact_at',{ascending:false}); setClients(data||[]); if(!selected&&data?.[0]) setSelected(data[0]);};
 useEffect(()=>{load(); const ch=db.channel('dashboard').on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>load()).subscribe(); return()=>{db.removeChannel(ch)}},[]);
 useEffect(()=>{if(!selected)return; (async()=>{const {data:c}=await db.from('conversations').select('id,client_id,control_mode,handoff_reason,last_message_at').eq('client_id',selected.id).order('last_message_at',{ascending:false}).limit(1).maybeSingle();setConversation(c); if(c){const {data:m}=await db.from('messages').select('id,role,content,created_at').eq('conversation_id',c.id).order('created_at');setMessages(m||[])}})()},[selected]);
 useEffect(()=>{if(!conversation)return; const ch=db.channel('chat-'+conversation.id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${conversation.id}`},payload=>{if(payload.eventType==='INSERT')setMessages(x=>[...x,payload.new as Message])}).subscribe(); return()=>{db.removeChannel(ch)}},[conversation]);
 const setMode=async(mode:string)=>{if(!conversation)return; await db.from('conversations').update({control_mode:mode,status:mode==='human'?'human_active':mode==='ai'?'ai_active':'human_requested'}).eq('id',conversation.id);setConversation({...conversation,control_mode:mode});};
 const send=async()=>{if(!text.trim()||!conversation)return; const value=text.trim();setText(''); await db.from('messages').insert({conversation_id:conversation.id,role:'human',content:value}); await setMode('human');};
 return <main><header><div><div className="eyebrow">AI-МЕНЕДЖЕР</div><h1>Дмитрий AI</h1></div><div className="online">● Онлайн</div></header><section className="layout"><aside><div className="search">⌕ Поиск клиентов</div>{clients.map(x=><button className={'client '+(selected?.id===x.id?'active':'')} onClick={()=>setSelected(x)} key={x.id}><div><strong>{x.preferred_name||x.name||'Без имени'}</strong><span>{x.lead_stage||'new'}</span></div><small>{x.service_interest||'Новый диалог'}</small></button>)}</aside><article><div className="chatHead"><div><h2>{selected?.preferred_name||selected?.name||'Клиент'}</h2><p>{conversation?.control_mode==='ai'?'🤖 AI':conversation?.control_mode==='handoff'?'🔴 Нужен Дмитрий':'👤 Дмитрий'}</p></div><div className="actions"><button className="take" onClick={()=>setMode('human')}>Взять диалог</button><button onClick={()=>setMode('ai')}>Вернуть AI</button></div></div><div className="messages">{messages.map(m=><div key={m.id} className={'bubble '+(m.role==='client'?'clientMsg':m.role==='human'?'humanMsg':'aiMsg')}>{m.content}</div>)}</div><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Написать клиенту…"/><button onClick={send}>Отправить</button></div></article><aside className="profile"><div className="avatar">{(selected?.preferred_name||selected?.name||'К').slice(0,2).toUpperCase()}</div><h2>{selected?.preferred_name||selected?.name||'Клиент'}</h2><p>{selected?.username?`@${selected.username}`:'Telegram'}</p><hr/><label>Стадия</label><b>{selected?.lead_stage||'Новый клиент'}</b><label>Услуга</label><b>{selected?.service_interest||'Не указана'}</b><label>Бюджет</label><b>{selected?.budget||'Не указан'}</b><label>Последняя договорённость</label><b>{selected?.last_agreement||'Нет'}</b>{conversation?.handoff_reason&&<><label>Запрос</label><b>{conversation.handoff_reason}</b></>}</aside></section></main> }